// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sicnabtddhownaaindhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpY25hYnRkZGhvd25hYWluZGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzA1NDksImV4cCI6MjA2NTQ0NjU0OX0.41AmwYi4LUkCpal-olUUEkzUgnErdvNhY3tUAkBYtyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);